// Classify a repo file into a category and decide whether it is "trim" (bloats an
// AI coding tool's context for little value) or "keep" (real source you want seen).
import { basename, extname } from "node:path";

// Directories that are almost never useful in an agent's context.
export const VENDOR_DIRS = [
  "node_modules", "vendor", "bower_components", ".venv", "venv", "env",
  "__pycache__", ".git", ".hg", ".svn", ".pnp", ".yarn", ".gradle", ".mvn",
];
export const BUILD_DIRS = [
  "dist", "build", "out", ".next", ".nuxt", ".output", ".svelte-kit",
  "target", "coverage", ".turbo", ".cache", "__snapshots__", ".angular",
  ".terraform", "Pods", "DerivedData",
];

const LOCKFILES = new Set([
  "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "npm-shrinkwrap.json",
  "cargo.lock", "poetry.lock", "gemfile.lock", "composer.lock", "go.sum",
  "pubspec.lock", "podfile.lock", "packages.lock.json", "flake.lock", "uv.lock",
]);

const DATA_EXT = new Set([
  ".csv", ".tsv", ".parquet", ".ndjson", ".jsonl", ".sqlite", ".sqlite3",
  ".db", ".dump", ".pkl", ".npy", ".npz", ".arrow", ".feather", ".geojson",
]);

const BINARY_EXT = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".tiff",
  ".pdf", ".zip", ".gz", ".tar", ".tgz", ".7z", ".rar", ".jar", ".war",
  ".woff", ".woff2", ".ttf", ".otf", ".eot", ".mp3", ".mp4", ".mov", ".avi",
  ".wasm", ".so", ".dylib", ".dll", ".exe", ".bin", ".class", ".pyc",
  ".node", ".o", ".a", ".lib", ".psd", ".sketch", ".ai",
]);

const MINIFIED = /\.(min\.(js|css|mjs)|bundle\.js|map)$/i;
const GENERATED_MARKERS = /(@generated\b|DO NOT EDIT|Code generated by|autogenerated|@auto-generated)/;

const dirParts = (rel) => rel.split(/[\\/]/).slice(0, -1);

/**
 * @returns {{category:string, trim:boolean, binary:boolean, reason:string}}
 * category ∈ vendored|build|lockfile|minified|data|generated|large|binary|source
 */
