// Classify a repo file into a category and decide whether it is "trim" (bloats an
// AI coding tool's context for little value) or "keep" (real source you want seen).
import { basename, extname } from "node:path";

// Directories that are almost never useful in an agent's context.
export const VENDOR_DIRS = [
  "node_modules", "vendor", "bower_components", ".venv", "venv", "env",
  "__pycache__", ".git", ".hg", ".svn", ".pnp", ".yarn", ".gradle", ".mvn",
];
export const BUILD_DIRS = [
  "dist", "build", "out", ".next", ".nuxt", ".output", ".svelte-kit",
  "target", "coverage", ".turbo", ".cache", "__snapshots__", ".angular",
  ".terraform", "Pods", "DerivedData",
];

const LOCKFILES = new Set([
  "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "npm-shrinkwrap.json",
  "cargo.lock", "poetry.lock", "gemfile.lock", "composer.lock", "go.sum",
  "pubspec.lock", "podfile.lock", "packages.lock.json", "flake.lock", "uv.lock",
]);

const DATA_EXT = new Set([
  ".csv", ".tsv", ".parquet", ".ndjson", ".jsonl", ".sqlite", ".sqlite3",
  ".db", ".dump", ".pkl", ".npy", ".npz", ".arrow", ".feather", ".geojson",
]);

const BINARY_EXT = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".tiff",
  ".pdf", ".zip", ".gz", ".tar", ".tgz", ".7z", ".rar", ".jar", ".war",
  ".woff", ".woff2", ".ttf", ".otf", ".eot", ".mp3", ".mp4", ".mov", ".avi",
  ".wasm", ".so", ".dylib", ".dll", ".exe", ".bin", ".class", ".pyc",
  ".node", ".o", ".a", ".lib", ".psd", ".sketch", ".ai",
]);

const MINIFIED = /\.(min\.(js|css|mjs)|bundle\.js|map)$/i;
const GENERATED_MARKERS = /(@generated\b|DO NOT EDIT|Code generated by|autogenerated|@auto-generated)/;

const dirParts = (rel) => rel.split(/[\\/]/).slice(0, -1);

/**
 * @returns {{category:string, trim:boolean, binary:boolean, reason:string}}
 * category ∈ vendored|build|lockfile|minified|data|generated|large|binary|source
 */
export function classify(rel, { size = 0, tokens = 0, sample = "", maxTokens = 2000 }) {
  const name = basename(rel).toLowerCase();
  const ext = extname(name);
  const parts = dirParts(rel).map((p) => p.toLowerCase());

  if (BINARY_EXT.has(ext)) return { category: "binary", trim: true, binary: true, reason: "binary asset (skipped by agents, excluded to be safe)" };
  if (parts.some((p) => VENDOR_DIRS.includes(p))) return { category: "vendored", trim: true, binary: false, reason: "vendored dependency directory" };
  if (parts.some((p) => BUILD_DIRS.includes(p))) return { category: "build", trim: true, binary: false, reason: "build / generated output directory" };
  if (LOCKFILES.has(name)) return { category: "lockfile", trim: true, binary: false, reason: "dependency lockfile" };
  if (MINIFIED.test(name)) return { category: "minified", trim: true, binary: false, reason: "minified / bundled / sourcemap" };
  if (DATA_EXT.has(ext)) return { category: "data", trim: true, binary: false, reason: "data file" };
  if (sample && GENERATED_MARKERS.test(sample)) return { category: "generated", trim: true, binary: false, reason: 'marked "generated / do not edit"' };
  // Large structured data masquerading as source (big JSON/YAML/XML/SVG).
  if ([".json", ".yaml", ".yml", ".xml", ".svg"].includes(ext) && tokens > maxTokens)
    return { category: "data", trim: true, binary: false, reason: `large ${ext.slice(1)} (${fmt(tokens)} tokens)` };
  // Anything else that is simply huge is worth flagging (kept as a soft "large").
  if (tokens > maxTokens * 4)
    return { category: "large", trim: true, binary: false, reason: `very large file (${fmt(tokens)} tokens)` };
  return { category: "source", trim: false, binary: false, reason: "source" };
}

const fmt = (n) => (n >= 1000 ? (n / 1000).toFixed(n >= 10000 ? 0 : 1).replace(/\.0$/, "") + "k" : "" + n);
export { fmt };

/** Ignore glob for a path/category (dir categories collapse to the top dir). */
export function ignorePattern(rel) {
  const parts = rel.split(/[\\/]/);
  const lower = parts.map((p) => p.toLowerCase());
  for (const d of [...VENDOR_DIRS, ...BUILD_DIRS]) {
    const i = lower.indexOf(d);
    if (i !== -1) return parts.slice(0, i + 1).join("/") + "/";
  }
  return rel;
}
